### ISSUE TITLE
Update description of this repo

### ISSUE THREAD

**Issue by bocharsky-bw** [php-translation/documentation#27]
Let's add a link to the http://php-translation.readthedocs.io/en/latest/ in the repo description.

Now I see only:
> No description, website, or topics provided.

<img width="374" alt="screen shot 2017-12-30 at 10 57 24" src="https://user-images.githubusercontent.com/3317635/34452811-4558fb3a-ed50-11e7-9a93-73a4aaf5690f.png">

**Comment by Nyholm** [comment]
Thank you!
