### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Suvres** [php-translation/documentation#51]
[Documentation](https://php-translation.readthedocs.io/en/latest/symfony/extracting-translations.html) for "Extracting Translations from Source" is incomplete. 

![image](https://user-images.githubusercontent.com/67355511/88891505-a0c30a80-d243-11ea-80cf-6029931c60e6.png)

This makes it difficult to work with the package.

**Comment by welcoMattic** [comment]
Hi,

This part of the documentation is not complete, I agree. But if you have to extract translation from sources, you can use the symfony command to do it: https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically

**Comment by Suvres** [comment]
Hi, 
Thanks @welcoMattic for reply, but I search way to register custom Extractor in symfony app

**Comment by Suvres** [comment]
Ok, I found this in Your code
