### ISSUE TITLE
Page https://php-translation.readthedocs.io/ out of date

### ISSUE THREAD

**Issue by Suvres** [php-translation/documentation#53]
Hi,
Your site [https://php-translation.readthedocs.io/](https://php-translation.readthedocs.io/) is out of date, to the content in the repository

**Comment by bocharsky-bw** [comment]
Hey @Suvres ! Could you be more explicit? Any concrete examples that could help to debug it? Any link to the problem page? Because the main page you linked looks OK for me

**Comment by Suvres** [comment]
Hi,
[https://php-translation.readthedocs.io/en/latest/symfony/extracting-translations.html](https://php-translation.readthedocs.io/en/latest/symfony/extracting-translations.html) is out of date. Maybe You don't build your site in your domain ??

**Comment by bocharsky-bw** [comment]
Now I see it's out of sync with https://github.com/php-translation/documentation/blob/master/symfony/extracting-translations.rst - thanks for head ups!

@Nyholm could you check if we still have automated builds/deploys for our docs website?

**Comment by Suvres** [comment]
No problem

**Comment by Nyholm** [comment]
Thank you for the ping. 

Readthedocs didnt manage the webhook properly. I've triggered a build and added a new webhook. Is everything up to date now?

**Comment by Suvres** [comment]
Yes, everything is sync now :D
